### ISSUE TITLE
too much stuff in one dialog 

### ISSUE THREAD

**Issue by mircealungu** [zeeguu-ecosystem/Unified-Multilanguage-Reader#332]
![screenshot 2018-06-08 23 18 26](https://user-images.githubusercontent.com/464519/41181520-4c9dae40-6b72-11e8-9df6-3e7cc1810947.png)

the dialog window feels a bit like a CatDog... 

i wonder if it wouldn't be better to have two separate buttons...
+ Topics
+ Searches

the first would be the top of the panel and the second would be the bottom of the panel...
(probably the same with the other dialog: 
+ Topic Filter
+ Search Filter

what do you think?

**Comment by Feikoritsema** [comment]
So you mean adding 2 extra buttons in the sidebar and splitting the normal topics from the search topics ? 

I kind of agree with the fact that it would probably look better, though it also makes the process of following a search a bit harder. That's why I created the two buttons underneath the search bar at first.

I'll think about it and come back to you when I've made the other changes.

**Comment by Feikoritsema** [comment]
This is resolved.
